<?php

/**
 * $Id: xoops_version.php,v 1.1 2003/10/15 05:36:46 mikhail Exp $
 *
 * @version   $Revision: 1.1 $
 * @author    Jochen Buennagel <jb at buennagel dot com>
 * @copyright copyright (c) 2003 by Jochen Buennagel
 *
 * This file is part of MetaCat, a category management module for Xoops
 *
 * MetaCat is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * MetaCat is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * Module Information data
 *
 * @var array
 */
$modversion['name'] = _MI_METACAT_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_METACAT_DESC;
$modversion['author'] = 'Jochen Bünnagel';
$modversion['credits'] = 'Development funded by:<br>Stuurgroep Experimenten Volkshuisvesting (sev.nl)<br>for wijkwebsites.nl';
$modversion['help'] = 'metacat.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/metacat_slogo.png';
$modversion['dirname'] = 'metacat';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'metacat_categories';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Blocks
$modversion['blocks'][1]['file'] = 'metacat_block.php';
$modversion['blocks'][1]['name'] = _MI_METACAT_BLOCK;
$modversion['blocks'][1]['description'] = 'Shows links in the same category';
$modversion['blocks'][1]['show_func'] = 'metacat_block_show';
$modversion['blocks'][1]['template'] = 'metacat_block.html';
// Menu
$modversion['hasMain'] = 0;
// Search
$modversion['hasSearch'] = 0;
// Comments
$modversion['hasComments'] = 0;
// Notification
$modversion['hasNotification'] = 0;
